resources:
  - dashboard-configmap.yaml
  - podmonitor.yaml

configMapGenerator:
  - name: caretta-dashboard
    namespace: monitoring
    files:
      - ../../grafana_dashboards/caretta-dashboard.json

generatorOptions:
  disableNameSuffixHash: true